services:
  - type: web
    name: cardgenerator-license-server
    runtime: python
    plan: free
    buildCommand: pip install -r server_requirements.txt
    startCommand: gunicorn server:app
    autoDeploy: true
